# 下記gemを追加して下さい
group :development do
  # Capistrano
  gem "capistrano", "~> 3.11", require: false 
  gem "capistrano-rails", "~> 1.4", require: false
  gem 'capistrano3-puma', require: false

  # net-ssh error https://github.com/net-ssh/net-ssh/issues/565
  gem 'ed25519'
  gem 'bcrypt_pbkdf'
end

# 下記gemもデフォルトだとコメントアウトされているのでコメント解除
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'mini_racer', platforms: :ruby